# Generated by Django 5.2 on 2025-04-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
    ]
