# Generated by Django 5.2 on 2025-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
